### ISSUE TITLE
Design docs? Code? usage?

### ISSUE THREAD

**Issue by dlcarmean** [davidteter/OPEN-RISOP#1]
I'm trying to explore this data, and my first pass at trying to load it into a relational database (sqlite) is failing due to duplicate lat/long values.  This brings me to a few questions:

1: are you using any DBMS back-end, or no?  Do you intend to at some point?

2: what tools and/or code are you using to process this and render graphics, and build the KML?

3: Can you say anything about the provenance of the target site data?

Thanks.

**Comment by davidteter** [comment]
Hi David,
Thanks for reaching out. I will do my best to try and respond to your questions. First of all, I'm a former nuclear war planner, intelligence analyst, and weapons designer. I spent my career focusing on adversary targets but was alway curious about "What would/could they do to us?" The US used to have a project called the Red Integrated Strategic Operational Plan (RISOP) that we would game against the US nuclear war plan (Single Integrated Operational Plan; SIOP). Back in the early-2000s, the US Department of Defense started pulling resources away from the RISOP to instead focus on the "Global War on Terror". I left that work in 2010, but always wondered about what the targets were here, so I started building the target database. At first it was an ad hoc process, but when the Department of Homeland Security GIS data under the Homeland Infrastructure Foundation-Level Data (HIFLD) program, data collection became easer, but data analyses (especially nodal analysis) became more of the issue.
1. Regarding DBMS... Probably not. In my opinion, the complexity level of the data set really doesn't warrant that. There are only approximately 10,000 targets in the database. The project is MIT licensed. You are more than welcome to build a DB however you see fit. Also, there shouldn't be lat/long duplicates in the target database except when a certain facility has multiple functions/purposes/etc. There are duplicates in the laydown files, but that's because sometimes a designated ground zero (DGZ) gets more than one nuke.
2. I'm using QGIS to build the target graphics. I actually use a third-party site (earthpoint.us) to transform the target databases and laydown files to build KML. Someone emailed me today that they have built a Python app. Whatever works.
3. Yes, I built it. All of it. I have deep knowledge of nuclear targeting and operations. Is this what the Russian nuclear war plan is? Who knows. I tried to learn that information back when I was in the IC, but even with a fuckton of clearances, no joy. 

I'm happy to try and answer any other questions and welcome any suggestions that you might have. Feel free to check out my bona fides on either LinkedIn or Twitter. Also, in the future, please contact me at david@davidteterconsulting.com instead of this channel (so that I see it).

Cheers,
David

**Comment by dlcarmean** [comment]
David,

Thanks for responding.  Firstly, I want to apologize for throwing a wet
towel on your "Flush the Bombers" thread; I wasn't sure what you meant by
that phrasing, and I pictured a Fail Safe scenario :/

Mostly, I tried putting this into a database so I could match the laydown
rows with the target db to understand them better.  I think I can still do
that by relaxing my table constraints.

In the past, I could have loaded them up in my Manifold GIS app but that
workstation is currently down/in storage; the current Mac barely has enough
memory for office work, so I haven't even thought about setting up qgis.

I grew up in Lompoc, hence my interest in Vandenberg.  I'm hearing rumors
from folks that used to work *all kinds* of launches out there that there
may be things in a couple of particular silos that would warrant a ground
burst.  And I don't mean the four Interceptor silos, if you get my drift.

Thanks for the reply.

**Comment by davidteter** [comment]
Ha. OK. 
I really like arguing, not to win, but to get others ideas that challenge me. That's all that post was. The problem with social media is that it's both filled with idiots and *extremely* knowledgable folks. That said, as painful as it is to engage with the "idiots", many of these folks have very good questions and opinions. Nuclear war is not about facts. It's just weird.

I did post a target graphic for Vandenberg SFB:
https://github.com/davidteter/OPEN-RISOP/blob/main/TARGET%20GRAPHICS/OPEN-RISOP%200.92%2020220224%20MAXIMUM%20COLLATERAL%20DAMAGE%20ATTACK/0.92%20MAX%20DAMAGE%20ATTACK%20CA_VANDENBURG%20SFB.png

That said, it's kind of generic. Despite all of the clearances that I held (past tense), a lot of the space shit is "ultra uber classified". Even holding some of those clearances, I have no idea of what really is going on. But that's just part of the game.

Once again, I will try and answer what I can and tell you if I cannot, but please use the email address that I sent you. 

Thanks,
David

**Comment by simonbargiora** [comment]
Why is Fordham college a target but not Yeshiva University?(in the Soviet plans to destroy US institutions of higher education)
