### ISSUE TITLE
Virginia Map

### ISSUE THREAD

**Issue by dakotamidnight** [davidteter/OPEN-RISOP#3]
Any chance of getting a full state map of Virginia? Based on multiple targets in the state?

This is the best mapping I've found & trying to judge risk levels for areas I'm looking at buying in.

**Comment by davidteter** [comment]
The project is still in "beta". Once it is done full maps will be posted. In the meantime, you are welcome to download and review the target database. FYI, I am a PhD/PE civil engineer and you are essentially asking me to provide free consulting. My normal billable rate is $300/hour. If you're interested, I can provide you with up to 3 county-specific damage maps along with what the likely issues would be in each county due to the destruction/damage of critical infrastructure for $1,200.
